version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"  # Fixed port mapping issue
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    command: ["node", "index.js"]
    env_file:
      - .env
    networks:
      - app_network  # Ensure it's on the same network as DB
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  # Ensure it’s accessible to the app
volumes:
  postgres_data:

networks:
  app_network: # Explicitly define the network